apiVersion: v1
kind: Service
metadata:
  name: davi-backend-service
spec:
  type: LoadBalancer # Supaya bisa dibuka di browser laptop
  selector:
    app: davi-backend
  ports:
    - protocol: TCP
      port: 8000 # Port browser (localhost:8000)
      targetPort: 80 # Port container (sesuai Dockerfile tadi)
