apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: davi-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: davi-backend-deploy
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
