name: CI/CD Bus Pariwisata

on:
  push:
    branches: ["main"] # Robot jalan otomatis pas Abang push ke branch 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Ambil kodingan terbaru dari GitHub
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Login ke Docker Hub pake kunci rahasia tadi
      - name: Login ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 3. Masak & Upload BACKEND
      - name: Build & Push Backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend # <-- Pastikan ini sesuai nama folder backend abang
          push: true
          tags: aryawrdn/backend-app:latest

      # 4. Masak & Upload FRONTEND
      - name: Build & Push Frontend
        uses: docker/build-push-action@v4
        with:
          context: ./toba2 # <-- Pastikan ini sesuai nama folder frontend abang
          push: true
          tags: aryawrdn/frontend-app:latest
