name: CI/CD Bus Pariwisata
on:
  push:
    branches: ["main"] # Jalan otomatis setiap kamu push ke branch main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Simulating
        run: |
          echo "Building Docker Image..."
          echo "Image davi-backend:latest ready!"

      - name: Deploy to Kubernetes Simulating
        run: |
          echo "Connecting to Cluster..."
          echo "Updating Deployment davi-backend-deploy..."
          echo "Success! Application Updated."
